var placetoVisit = ["SaudiArabia", "UK", "UAE", "SouthKorea", "Turkey"];
// console.log(placetoVisit);
// console.log(placetoVisit.sort());
// console.log(placetoVisit);
// console.log(placetoVisit.sort().reverse());
// console.log(placetoVisit);
// console.log(placetoVisit.reverse());
// console.log(placetoVisit.reverse());
var sortedArray = ["SaudiArabia", "UK", "UAE", "SouthKorea", "Turkey"];
sortedArray.sort();
console.log(sortedArray);
sortedArray.reverse();
console.log(sortedArray);
